// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 알림 히스토리 엔티티
 */
export type AlertHistory = { id: string, rule_id: string | null, signal_marker_id: string | null, alert_type: string, channel: string, status: string, title: string, message: string, metadata: Record<string, unknown>, error_message: string | null, retry_count: number, created_at: string, sent_at: string | null, acknowledged_at: string | null, acknowledged_by: string | null, };
