// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertHistory } from "./AlertHistory";

/**
 * 알림 히스토리 응답
 */
export type AlertHistoryResponse = { alerts: Array<AlertHistory>, total: bigint, limit: number, offset: number, };
