// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 알림 채널
 */
export type AlertChannel = "TELEGRAM" | "EMAIL" | "DISCORD" | "SLACK" | "WEBHOOK" | "SMS";
