// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 알림 통계
 */
export type AlertStats = { total_count: bigint, pending_count: bigint, sent_count: bigint, failed_count: bigint, acknowledged_count: bigint, };
