// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Score History 조회 쿼리
 */
export type ScoreHistoryQuery = { 
/**
 * 조회 일수 (기본 90, 최대 365)
 */
days: number, };
