// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreHistorySummary } from "../repository/ScoreHistorySummary";

/**
 * Score History 응답
 */
export type ScoreHistoryResponse = { 
/**
 * 종목 코드
 */
symbol: string, 
/**
 * 히스토리 데이터
 */
history: Array<ScoreHistorySummary>, 
/**
 * 총 레코드 수
 */
total: number, };
