// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Score History 요약 (API 응답용).
 */
export type ScoreHistorySummary = { symbol: string, score_date: string, global_score: number | null, route_state: string | null, rank: number | null, score_change: number | null, rank_change: number | null, };
