// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략 거래소 계정 업데이트 요청.
 */
export type UpdateCredentialRequest = { 
/**
 * 새로운 거래소 계정 ID (NULL이면 연결 해제)
 */
credentialId?: string, 
/**
 * 대상 시장 (KR/US/CRYPTO)
 */
market?: string, };
