// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mock 스트리밍 설정 DTO.
 */
export type MockStreamingConfigDto = { 
/**
 * 가격 생성 모드 ("random_walk" | "historical_replay" | "yahoo_legacy")
 */
mode: string | null, 
/**
 * 틱 발생 간격 (밀리초, 기본 1000)
 */
tickIntervalMs?: number, 
/**
 * 재생 속도 (HistoricalReplay 전용, 기본 1.0)
 */
replaySpeed?: number, 
/**
 * 스프레드 배율 (기본 1.0)
 */
spreadMultiplier?: number, 
/**
 * 호가창 기본 잔량 (기본 100)
 */
orderbookBaseVolume?: number, };
