// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaperTradingPosition } from "./PaperTradingPosition";

/**
 * Paper Trading 포지션 목록 응답.
 */
export type PaperTradingPositionsResponse = { 
/**
 * 포지션 목록
 */
positions: Array<PaperTradingPosition>, 
/**
 * 총 포지션 수
 */
total: number, 
/**
 * 총 평가액
 */
totalValue: string, 
/**
 * 총 미실현 손익
 */
totalUnrealizedPnl: string, };
