// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MockStreamingConfigDto } from "./MockStreamingConfigDto";

/**
 * Paper Trading 시작 요청.
 */
export type PaperTradingStartRequest = { 
/**
 * 사용할 Mock 계정 ID
 */
credentialId: string, 
/**
 * 초기 잔고 (옵션, 없으면 계정 기본값)
 */
initialBalance?: number, 
/**
 * 스트리밍 설정 (옵션, 없으면 YahooLegacy 모드)
 */
streamingConfig?: MockStreamingConfigDto, };
