// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaperTradingExecution } from "./PaperTradingExecution";

/**
 * Paper Trading 체결 내역 응답.
 */
export type PaperTradingExecutionsResponse = { 
/**
 * 체결 내역
 */
executions: Array<PaperTradingExecution>, 
/**
 * 총 체결 수
 */
total: number, };
