// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper Trading 세션 상태 응답.
 */
export type PaperTradingSessionResponse = { 
/**
 * 전략 ID
 */
strategyId: string, 
/**
 * 계정 ID
 */
credentialId: string, 
/**
 * 상태 (running, stopped, paused)
 */
status: string, 
/**
 * 초기 잔고
 */
initialBalance: string, 
/**
 * 현재 잔고
 */
currentBalance: string, 
/**
 * 포지션 수
 */
positionCount: number, 
/**
 * 거래 수
 */
tradeCount: number, 
/**
 * 실현 손익
 */
realizedPnl: string, 
/**
 * 미실현 손익
 */
unrealizedPnl: string, 
/**
 * 수익률 (%)
 */
returnPct: string, 
/**
 * 시작 시간
 */
startedAt: string | null, };
