// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper Trading 체결 내역.
 */
export type PaperTradingExecution = { 
/**
 * 체결 ID
 */
id: string, 
/**
 * 심볼
 */
symbol: string, 
/**
 * 방향 (Buy/Sell)
 */
side: string, 
/**
 * 수량
 */
quantity: string, 
/**
 * 체결가
 */
price: string, 
/**
 * 수수료
 */
commission: string, 
/**
 * 실현 손익 (청산 시)
 */
realizedPnl: string | null, 
/**
 * 체결 시간
 */
executedAt: string, };
