// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 신호 타입별 통계
 */
export type SignalTypeStats = { 
/**
 * 신호 타입 (Entry, Exit 등)
 */
signal_type: string, 
/**
 * 방향 (Buy, Sell)
 */
side: string | null, 
/**
 * 총 신호 수
 */
total_signals: bigint, 
/**
 * 승리 횟수
 */
win_count: bigint, 
/**
 * 패배 횟수
 */
loss_count: bigint, 
/**
 * 승률 (%)
 */
win_rate: number | null, 
/**
 * 평균 1일 수익률 (%)
 */
avg_return_1d: number | null, 
/**
 * 평균 5일 수익률 (%)
 */
avg_return_5d: number | null, 
/**
 * 평균 10일 수익률 (%)
 */
avg_return_10d: number | null, 
/**
 * 평균 MFE (%)
 */
avg_max_return: number | null, 
/**
 * 평균 MAE (%)
 */
avg_max_drawdown: number | null, };
