// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략별 신호 통계
 */
export type SignalStrategyStats = { 
/**
 * 전략 ID
 */
strategy_id: string, 
/**
 * 총 신호 수
 */
total_signals: bigint, 
/**
 * 승리 횟수
 */
win_count: bigint, 
/**
 * 승률 (%)
 */
win_rate: number | null, 
/**
 * 평균 1일 수익률 (%)
 */
avg_return_1d: number | null, 
/**
 * 평균 5일 수익률 (%)
 */
avg_return_5d: number | null, 
/**
 * 평균 신호 강도
 */
avg_strength: number | null, 
/**
 * 평균 MFE (%)
 */
avg_mfe: number | null, 
/**
 * 평균 MAE (%)
 */
avg_mae: number | null, };
