// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalStrategyStats } from "./SignalStrategyStats";
import type { SignalStrengthStats } from "./SignalStrengthStats";
import type { SignalSymbolStats } from "./SignalSymbolStats";
import type { SignalTypeStats } from "./SignalTypeStats";

/**
 * 신호 성과 종합 응답
 */
export type SignalPerformanceResponse = { 
/**
 * 타입별 통계
 */
type_stats: Array<SignalTypeStats>, 
/**
 * 강도별 통계
 */
strength_stats: Array<SignalStrengthStats>, 
/**
 * 심볼별 통계 (상위 10개)
 */
symbol_stats: Array<SignalSymbolStats>, 
/**
 * 전략별 통계
 */
strategy_stats: Array<SignalStrategyStats>, 
/**
 * 총 분석 대상 신호 수
 */
total_analyzed: bigint, 
/**
 * 전체 승률 (%)
 */
overall_win_rate: number | null, 
/**
 * 전체 평균 수익률 (%)
 */
overall_avg_return: number | null, };
