// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 신호-수익률 상관관계 데이터 포인트 (산점도용)
 */
export type SignalReturnPoint = { 
/**
 * 신호 ID
 */
signal_id: string, 
/**
 * 신호 강도 (0-1)
 */
strength: number, 
/**
 * 5일 수익률 (%)
 */
return_5d: number | null, 
/**
 * 신호 타입
 */
signal_type: string, 
/**
 * 방향
 */
side: string | null, 
/**
 * 종목 코드
 */
ticker: string, };
