//! Strategy module for implementing trading strategies

use crate::types::{MarketData, Order, OrderSide, OrderType};
use chrono::Utc;

/// Trading signal generated by a strategy
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Signal {
    Buy,
    Sell,
    Hold,
}

/// Trait that all trading strategies must implement
pub trait Strategy: Send + Sync {
    /// Analyze market data and generate a trading signal
    fn analyze(&mut self, data: &MarketData) -> Signal;

    /// Get the strategy name
    fn name(&self) -> &str;

    /// Reset strategy state
    fn reset(&mut self);
}

/// Simple moving average crossover strategy
pub struct MovingAverageCrossover {
    short_period: usize,
    long_period: usize,
    short_prices: Vec<f64>,
    long_prices: Vec<f64>,
}

impl MovingAverageCrossover {
    pub fn new(short_period: usize, long_period: usize) -> Self {
        Self {
            short_period,
            long_period,
            short_prices: Vec::new(),
            long_prices: Vec::new(),
        }
    }

    fn calculate_sma(prices: &[f64], period: usize) -> Option<f64> {
        if prices.len() < period {
            return None;
        }
        let sum: f64 = prices.iter().rev().take(period).sum();
        Some(sum / period as f64)
    }
}

impl Strategy for MovingAverageCrossover {
    fn analyze(&mut self, data: &MarketData) -> Signal {
        self.short_prices.push(data.close);
        self.long_prices.push(data.close);

        let short_ma = Self::calculate_sma(&self.short_prices, self.short_period);
        let long_ma = Self::calculate_sma(&self.long_prices, self.long_period);

        // Keep only necessary history
        if self.short_prices.len() > self.long_period * 2 {
            self.short_prices.remove(0);
            self.long_prices.remove(0);
        }

        match (short_ma, long_ma) {
            (Some(short), Some(long)) => {
                if short > long {
                    Signal::Buy
                } else if short < long {
                    Signal::Sell
                } else {
                    Signal::Hold
                }
            }
            _ => Signal::Hold,
        }
    }

    fn name(&self) -> &str {
        "MovingAverageCrossover"
    }

    fn reset(&mut self) {
        self.short_prices.clear();
        self.long_prices.clear();
    }
}

/// Helper function to create an order from a signal
pub fn create_order_from_signal(
    signal: Signal,
    symbol: &str,
    quantity: f64,
    price: Option<f64>,
) -> Option<Order> {
    match signal {
        Signal::Buy => Some(Order {
            id: format!("order_{}", uuid::Uuid::new_v4()),
            symbol: symbol.to_string(),
            side: OrderSide::Buy,
            order_type: if price.is_some() { OrderType::Limit } else { OrderType::Market },
            quantity,
            price,
            timestamp: Utc::now(),
        }),
        Signal::Sell => Some(Order {
            id: format!("order_{}", uuid::Uuid::new_v4()),
            symbol: symbol.to_string(),
            side: OrderSide::Sell,
            order_type: if price.is_some() { OrderType::Limit } else { OrderType::Market },
            quantity,
            price,
            timestamp: Utc::now(),
        }),
        Signal::Hold => None,
    }
}
